import {
  ActionButton,
  AlarmPanel,
  BinaryBadge,
  CalendarCard,
  ClimateCard,
  CounterCard,
  CoverCard,
  DeviceTrackerChip,
  EntityRow,
  FanCard,
  Gauge,
  HumidifierCard,
  InputBooleanTile,
  LightTile,
  LockCard,
  MediaPlayerCard,
  NumberSlider,
  PersonChip,
  SceneButton,
  ScriptButton,
  SelectCard,
  SirenCard,
  TimerCard,
  UpdateCard,
  VacuumCard,
  ValveCard,
  WaterHeaterCard,
  WeatherCard,
} from '../cards/domain';
import type { WidgetCatalogEntry } from './types';
import { CameraDemo, pickNumericSensorEntity, SparkDemo, StatDemo } from './demos';

/** Entity-bound cards — one widget per HA domain (implementations in `cards/domain/`). */
export const DOMAIN_WIDGET_CATALOG: WidgetCatalogEntry[] = [
  {
    name: 'Stat',
    label: 'Stat',
    category: 'domain',
    domains: ['sensor'],
    snippet: (id) =>
      `<Stat label="${id.split('.')[1] ?? 'Sensor'}" value={num(useEntity('${id}')?.state)} />`,
    Demo: StatDemo,
  },
  {
    name: 'Gauge',
    label: 'Gauge',
    category: 'domain',
    domains: ['sensor'],
    inserterDefault: true,
    snippet: (id) => `<Gauge entityId="${id}" min={0} max={100} />`,
    Demo: Gauge,
  },
  {
    name: 'SparkChart',
    label: 'SparkChart',
    category: 'domain',
    domains: ['sensor'],
    pickExample: pickNumericSensorEntity,
    snippet: '<SparkChart series={[…]} height={120} axes={{ xLabel: "Zeit", yLabel: "W" }} />',
    Demo: SparkDemo,
  },
  {
    name: 'EntityRow',
    label: 'Entity-Zeile',
    category: 'domain',
    domains: ['switch'],
    inserterDefault: true,
    snippet: (id) => `<EntityRow entityId="${id}" />`,
    Demo: EntityRow,
  },
  {
    name: 'BinaryBadge',
    label: 'Binary',
    category: 'domain',
    domains: ['binary_sensor'],
    inserterDefault: true,
    snippet: (id) => `<BinaryBadge entityId="${id}" />`,
    Demo: BinaryBadge,
  },
  {
    name: 'LightTile',
    label: 'Licht',
    category: 'domain',
    domains: ['light'],
    inserterDefault: true,
    snippet: (id) => `<LightTile entityId="${id}" showBrightness />`,
    Demo: LightTile,
  },
  {
    name: 'ClimateCard',
    label: 'Klima',
    category: 'domain',
    domains: ['climate'],
    inserterDefault: true,
    snippet: (id) => `<ClimateCard entityId="${id}" />`,
    Demo: ClimateCard,
  },
  {
    name: 'CoverCard',
    label: 'Rollo',
    category: 'domain',
    domains: ['cover'],
    inserterDefault: true,
    snippet: (id) => `<CoverCard entityId="${id}" />`,
    Demo: CoverCard,
  },
  {
    name: 'MediaPlayerCard',
    label: 'Media',
    category: 'domain',
    domains: ['media_player'],
    inserterDefault: true,
    snippet: (id) => `<MediaPlayerCard entityId="${id}" />`,
    Demo: MediaPlayerCard,
  },
  {
    name: 'WeatherCard',
    label: 'Wetter',
    category: 'domain',
    domains: ['weather'],
    inserterDefault: true,
    snippet: (id) => `<WeatherCard entityId="${id}" showWind />`,
    Demo: WeatherCard,
  },
  {
    name: 'PersonChip',
    label: 'Person',
    category: 'domain',
    domains: ['person'],
    inserterDefault: true,
    snippet: (id) => `<PersonChip entityId="${id}" />`,
    Demo: PersonChip,
  },
  {
    name: 'DeviceTrackerChip',
    label: 'Tracker',
    category: 'domain',
    domains: ['device_tracker'],
    inserterDefault: true,
    snippet: (id) => `<DeviceTrackerChip entityId="${id}" />`,
    Demo: DeviceTrackerChip,
  },
  {
    name: 'NumberSlider',
    label: 'Zahl',
    category: 'domain',
    domains: ['input_number'],
    inserterDefault: true,
    snippet: (id) => `<NumberSlider entityId="${id}" min={0} max={100} step={1} />`,
    Demo: NumberSlider,
  },
  {
    name: 'InputBooleanTile',
    label: 'Schalter',
    category: 'domain',
    domains: ['input_boolean'],
    inserterDefault: true,
    snippet: (id) => `<InputBooleanTile entityId="${id}" />`,
    Demo: InputBooleanTile,
  },
  {
    name: 'ActionButton',
    label: 'Aktion',
    category: 'domain',
    domains: ['button', 'automation'],
    snippet: (id) => `<ActionButton entityId="${id}" />`,
    Demo: ActionButton,
  },
  {
    name: 'SceneButton',
    label: 'Szene',
    category: 'domain',
    domains: ['scene'],
    inserterDefault: true,
    snippet: (id) => `<SceneButton entityId="${id}" />`,
    Demo: SceneButton,
  },
  {
    name: 'ScriptButton',
    label: 'Skript',
    category: 'domain',
    domains: ['script'],
    inserterDefault: true,
    snippet: (id) => `<ScriptButton entityId="${id}" />`,
    Demo: ScriptButton,
  },
  {
    name: 'SelectCard',
    label: 'Auswahl',
    category: 'domain',
    domains: ['input_select', 'select'],
    inserterDefault: true,
    snippet: (id) => `<SelectCard entityId="${id}" />`,
    Demo: SelectCard,
  },
  {
    name: 'LockCard',
    label: 'Schloss',
    category: 'domain',
    domains: ['lock'],
    inserterDefault: true,
    snippet: (id) => `<LockCard entityId="${id}" />`,
    Demo: LockCard,
  },
  {
    name: 'VacuumCard',
    label: 'Staubsauger',
    category: 'domain',
    domains: ['vacuum'],
    inserterDefault: true,
    snippet: (id) => `<VacuumCard entityId="${id}" />`,
    Demo: VacuumCard,
  },
  {
    name: 'FanCard',
    label: 'Ventilator',
    category: 'domain',
    domains: ['fan'],
    inserterDefault: true,
    snippet: (id) => `<FanCard entityId="${id}" />`,
    Demo: FanCard,
  },
  {
    name: 'AlarmPanel',
    label: 'Alarm',
    category: 'domain',
    domains: ['alarm_control_panel'],
    inserterDefault: true,
    snippet: (id) => `<AlarmPanel entityId="${id}" />`,
    Demo: AlarmPanel,
  },
  {
    name: 'CameraTile',
    label: 'Kamera',
    category: 'domain',
    domains: ['camera'],
    inserterDefault: true,
    snippet: (id) => `<CameraTile entityId="${id}" refreshSec={10} fit="cover" />`,
    Demo: CameraDemo,
  },
  {
    name: 'TimerCard',
    label: 'Timer',
    category: 'domain',
    domains: ['timer'],
    inserterDefault: true,
    snippet: (id) => `<TimerCard entityId="${id}" />`,
    Demo: TimerCard,
  },
  {
    name: 'CounterCard',
    label: 'Zähler',
    category: 'domain',
    domains: ['counter'],
    inserterDefault: true,
    snippet: (id) => `<CounterCard entityId="${id}" />`,
    Demo: CounterCard,
  },
  {
    name: 'HumidifierCard',
    label: 'Luftbefeuchter',
    category: 'domain',
    domains: ['humidifier'],
    inserterDefault: true,
    snippet: (id) => `<HumidifierCard entityId="${id}" />`,
    Demo: HumidifierCard,
  },
  {
    name: 'WaterHeaterCard',
    label: 'Warmwasser',
    category: 'domain',
    domains: ['water_heater'],
    inserterDefault: true,
    snippet: (id) => `<WaterHeaterCard entityId="${id}" />`,
    Demo: WaterHeaterCard,
  },
  {
    name: 'ValveCard',
    label: 'Ventil',
    category: 'domain',
    domains: ['valve'],
    inserterDefault: true,
    snippet: (id) => `<ValveCard entityId="${id}" />`,
    Demo: ValveCard,
  },
  {
    name: 'SirenCard',
    label: 'Sirene',
    category: 'domain',
    domains: ['siren'],
    inserterDefault: true,
    snippet: (id) => `<SirenCard entityId="${id}" />`,
    Demo: SirenCard,
  },
  {
    name: 'UpdateCard',
    label: 'Update',
    category: 'domain',
    domains: ['update'],
    inserterDefault: true,
    snippet: (id) => `<UpdateCard entityId="${id}" />`,
    Demo: UpdateCard,
  },
  {
    name: 'CalendarCard',
    label: 'Kalender',
    category: 'domain',
    domains: ['calendar'],
    inserterDefault: true,
    snippet: (id) => `<CalendarCard entityId="${id}" />`,
    Demo: CalendarCard,
  },
];
